title: Jacob Whitehill's research group
description: Lab website of Prof. Jacob Whitehill, Worcester Polytechnic Institute (WPI), Massachusetts, USA
theme: jekyll-theme-minimal
google-site-verification: google4937499b98bb6bb1.html
